import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextUIProvider } from "@nextui-org/system";

import { Providers } from "./providers"
import './globals.css'
import NavBar from './components/nav-bar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Providers>
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  )
}
